version: '3'

services:
  nginx-rtmp:
    image: alfg/nginx-rtmp
    ports:
      - 2035:1935
      - 2036:80
    environment:
      - HTTP_PORT=80
      - RTMP_PORT=1935
    volumes:
      - ./certs:/opt/certs
      - ./nginx.conf:/etc/nginx/nginx.conf.template
